"""add_datetime_and_equipment_details

Revision ID: d7cd7327cf2b
Revises: 
Create Date: 2026-04-11 19:59:55.686071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'd7cd7327cf2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ── Step 1: Thêm 4 cột mới cho equipment ─────────────────────────────
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('usage',       sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('functions',   sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specs',       sa.Text(), nullable=True))

    # ── Step 2: Đổi kiểu cột Date → DateTime trong request ────────────────
    # SQLite lưu DATE dưới dạng text "YYYY-MM-DD", sau khi đổi sang DATETIME
    # Alembic/SQLite vẫn đọc được. Ta chạy UPDATE để gán thêm phần giờ.
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('borrow_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('return_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('actual_return_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ── Step 3: Data migration — thêm " 00:00:00" vào các cột date cũ ────
    conn = op.get_bind()
    conn.execute(text(
        "UPDATE request SET borrow_date = borrow_date || ' 00:00:00' "
        "WHERE borrow_date NOT LIKE '% %'"
    ))
    conn.execute(text(
        "UPDATE request SET return_date = return_date || ' 00:00:00' "
        "WHERE return_date NOT LIKE '% %'"
    ))
    conn.execute(text(
        "UPDATE request SET actual_return_date = actual_return_date || ' 00:00:00' "
        "WHERE actual_return_date IS NOT NULL AND actual_return_date NOT LIKE '% %'"
    ))

    # ── Step 4: Chuyển equipment.status='Borrowed' → 'Available' ──────────
    # Trạng thái Borrowed không còn dùng sau khi chuyển sang lịch theo giờ
    conn.execute(text(
        "UPDATE equipment SET status = 'Available' WHERE status = 'Borrowed'"
    ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('actual_return_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('return_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('borrow_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('specs')
        batch_op.drop_column('functions')
        batch_op.drop_column('usage')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
